# polymorphism

#### comes from greek word poly(many)+morpho(forms)

#### there are three method for achive

## method overriding
## operator overloading
## method overloading

# Operator overloading

In [9]:
print(1+2)
print("1"+"2")
print("bhumit" *3)

3
12
bhumitbhumitbhumit


In [10]:
print(int.__add__(1,2))

3


In [13]:
print(str.__add__("1","2"))

12


In [17]:
print(str.__mul__("hey ",3))

hey hey hey 


In [21]:
# Operator overloading for complex number
class Complex:
    def __init__(self,r,i):
        self.r=r
        self.i=i
    def __add__(self,other):
        r=self.r+other.r
        i=self.i+other.i
        return f"{r}+{i}i"
        
        
c1=Complex(1,4)
c2=Complex(3,5)
print(c1+c2)

4+9i


In [29]:
class A:
    def __init__(self,a):
        self.a=a
    def __gt__(self,other):
        if self.a>other.a:
            return f"{self.a} is higher"
        else:
            return f"{other.a} is higher"
    def __lt__(self,other):
        if self.a<other.a:
            return f"{self.a} is lower"
        else:
            return f"{other.a} is lower"
x = A(4)
y = A(30)
print(x>y)
print(x<y)

30 is higher
4 is lower


# Method overloading

In [39]:
class Addition:
    def sum(self,a,b):
        return a+b
    def sum(self,a,b,c=100):
        return a+b+c
obj=Addition()
print(obj.sum(4,5))
print(obj.sum(4,5,9))

109
18


In [43]:
class Addition:
    def sum(self,a,b):
        return a+b
    def sum(self,*args):
        return sum(args)
obj=Addition()
obj.sum(10,10,10,10,10)

50

In [46]:
import functools
dir(functools)

['RLock',
 'WRAPPER_ASSIGNMENTS',
 'WRAPPER_UPDATES',
 '_CacheInfo',
 '_HashedSeq',
 '_NOT_FOUND',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_c3_merge',
 '_c3_mro',
 '_compose_mro',
 '_convert',
 '_find_impl',
 '_ge_from_gt',
 '_ge_from_le',
 '_ge_from_lt',
 '_gt_from_ge',
 '_gt_from_le',
 '_gt_from_lt',
 '_initial_missing',
 '_le_from_ge',
 '_le_from_gt',
 '_le_from_lt',
 '_lru_cache_wrapper',
 '_lt_from_ge',
 '_lt_from_gt',
 '_lt_from_le',
 '_make_key',
 '_unwrap_partial',
 'cached_property',
 'cmp_to_key',
 'get_cache_token',
 'lru_cache',
 'namedtuple',
 'partial',
 'partialmethod',
 'recursive_repr',
 'reduce',
 'singledispatch',
 'singledispatchmethod',
 'total_ordering',
 'update_wrapper',
 'wraps']

# Method overriding (inheritance)

# Single inheritance

In [59]:
class Parent:
    def sleep(self):
        print("sleep at 9 pm")
class Child(Parent):
    def sleep(self):
        print("sleep at 12 am")
    def eat(self):
        print("eat at 8 am")
x=Parent()
x.sleep()


sleep at 9 pm


In [65]:
class Parent:
    def sleep(self):
        print("sleep at 9 pm")
class Child(Parent):
    def sleep(self):
        print("sleep at 12 am")
        super().sleep()
    def eat(self):
        print("eat at 8 am")
x=Child()
x.sleep()
x.eat()
print(Parent.mro())

sleep at 12 am
sleep at 9 pm
eat at 8 am
[<class '__main__.Parent'>, <class 'object'>]


In [64]:
class Parent:
    def sleep(self):
        print("sleep at 9 pm")
class Child(Parent):
    def swim(self):
        print("swim at 7 am")
    def eat(self):
        print("eat at 8 am")
x=Child()
x.swim()
x.eat()
print(Child.mro())

swim at 7 am
eat at 8 am
[<class '__main__.Child'>, <class '__main__.Parent'>, <class 'object'>]


# Multiple inheritance

In [79]:
class Father:
    def sleep(self):
         print("sleep at 10 pm")
    def swim(self):
        print("swim at 9 pm")
class Mother:
    def sleep(self):
        print("sleep at 10 am")
    def cook(self):
        print("cook very good")
class Child(Father,Mother):
    def run(self):
        print("RUN VERY SLOW")
x = Child()
x.run()
x.sleep()
x.cook()
x.swim()
print(Child.mro())

RUN VERY SLOW
sleep at 10 pm
cook very good
swim at 9 pm
[<class '__main__.Child'>, <class '__main__.Father'>, <class '__main__.Mother'>, <class 'object'>]


# Multilevel inheritance

In [85]:
class Car:
    def color(self):
        print("black")
class Audi(Car):
    def car_name(self):
        print("name is audi")
class Model(Audi):
    def car_model(self):
        print("q4")
x = Model()
x.color()
x.car_name()
x.car_model()
print(Model.mro())

black
name is audi
q4
[<class '__main__.Model'>, <class '__main__.Audi'>, <class '__main__.Car'>, <class 'object'>]


# Hierarchical inheritance

In [7]:
class Parent:
    def display(self):
        print("display parent")
class Child(Parent):
    def fun(self):
        print("fun at 7 am")
class Child2(Parent):
    def show(self):
        print("show at 7 am")
x=Child2()
y=Child()
y.fun()
x.show()
print(Child.mro())
print(Child2.mro())

fun at 7 am
show at 7 am
[<class '__main__.Child'>, <class '__main__.Parent'>, <class 'object'>]
[<class '__main__.Child2'>, <class '__main__.Parent'>, <class 'object'>]


# Hybrid inheritance

In [12]:
class Father:
    def f(self):
        print("father")
class Mother:
    def f1(self):
        print("mother")
class Child(Father,Mother):
    def display(self):
        print("child")
class dada_no_chokro(Child):
    def gc(self):
        print("grand child 1")
class dada_no_chokro2(Child):
    def gc2(self):
        print("grand child 2")
x=dada_no_chokro()
x.display()
x.f()
x.gc()
x.f1()
print("============")
x=dada_no_chokro2()
x.display()
x.f()
x.gc2()
x.f1()    
print("============")    
print(dada_no_chokro.mro())        

child
father
grand child 1
mother
child
father
grand child 2
mother
[<class '__main__.dada_no_chokro'>, <class '__main__.Child'>, <class '__main__.Father'>, <class '__main__.Mother'>, <class 'object'>]


In [19]:
class p1:
    def f(self):
        print("father")
class p2:
    def f1(self):
        print("mother")
class c1(p1,p2):
    def display(self):
        print("child")
class c2(p2):
    def gc(self):
        print("grand child 1")
class gc(c1,c2):
    def gc2(self):
        print("grand child 2")

print(gc.mro())

[<class '__main__.gc'>, <class '__main__.c1'>, <class '__main__.p1'>, <class '__main__.c2'>, <class '__main__.p2'>, <class 'object'>]


# Array

In [4]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [9]:
d=range(0,3)
print(d)

range(0, 3)


In [11]:
import sys
dir(sys)
sys.getsizeof(d)

48

In [18]:
import numpy as np
arr = np.arange(100)
print(arr)
print(arr.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
4


In [20]:
arr = np.array(42)
print(arr)
print(arr.ndim)

42
0


In [32]:
arr = np.array([[42]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[42]]
2
(1, 1)


In [34]:
arr = np.array([[[42,45]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[42 45]]]
3
(1, 1, 2)


In [50]:
arr = np.array([[42,22,66],[23,34,33]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.reshape(3,2))

[[42 22 66]
 [23 34 33]]
2
(2, 3)
[[42 22]
 [66 23]
 [34 33]]


In [52]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


# Accessing elements of array

In [55]:
arr = np.array([1,4,9,6,3,2])
print(arr[0])
print(arr[3])
print(arr[1:2])
arr1 = arr[1:2]
print(arr1.shape)

1
6
[4]
(1,)


In [62]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1])
print(arr[1,2])
print(arr[1,:2])
print(arr[:2,:2])

[4 5 6]
6
[4 5]
[[1 2]
 [4 5]]


In [70]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,2])
print()
print(arr[0,:2,2])
print()
print(arr[1,0:2,0:2])
print()
print(arr[0:2,1,1:2])
print()
print(arr[:2,:2,1])
print()
print(arr[:2,:2,:1])

9

[3 6]

[[ 7  8]
 [10 11]]

[[ 5]
 [11]]

[[ 2  5]
 [ 8 11]]

[[[ 1]
  [ 4]]

 [[ 7]
  [10]]]


In [86]:
arr = np.array([1,2,3,4,5,6])
arr1 = arr.reshape(2,-1)
print(arr1)

[[1 2 3]
 [4 5 6]]


# concatenate(), split(), where(), sort()

## concatenate()

In [5]:
import numpy as n
arr = n.array([1,2,3])
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
a1 = n.array([1,2,3])
a2 = n.array([4,5,6])
a3 = n.array([7,8,9])
newAr = n.concatenate((a1,a2,a3))
print(newAr)

[1 2 3 4 5 6 7 8 9]


In [14]:
a1 = n.array([1,2,3])
a2 = n.array([4,5,6])
a3 = n.array([7,8,9])
newAr = n.concatenate((a1,a2,a3),1)
print(newAr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [32]:
a1 = n.array([[1,2],[3,4]])
a2 = n.array([[5,6],[7,8]])
newAr = n.concatenate((a1,a2))
print(newAr)
print()
newAr = n.concatenate((a1,a2),1)
print(newAr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [37]:
a1 = n.array([[[1,2],[3,4]]])
a2 = n.array([[[1,2],[3,4]]])

newAr = n.concatenate((a1,a2))
print(newAr)
print()
newAr = n.concatenate((a1,a2),2)
print(newAr)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

[[[1 2 1 2]
  [3 4 3 4]]]


## split()

In [46]:
a = n.array([1,2,3,4,5,6])

print(n.array_split(a,3))
print(n.array_split(a,2))
print(n.array_split(a,4))
print(n.array_split(a,10))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [52]:
a = n.array([[1,2,3],[4,5,6],[7,8,9]])
print(n.array_split(a,2))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [58]:
a = n.array([[1,2,3],[4,5,6],[7,8,9]])
print(n.array_split(a,3,1))
print()
print(n.array_split(a,4,1))

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]]), array([], shape=(3, 0), dtype=int32)]


In [61]:
a = n.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(n.array_split(a,2,1))

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[7, 8, 9]]])]


## where()

In [67]:
a = n.array([1,3,3,4,5,3])
print(n.where(a == 3))
a = n.array([1,2,3,4,5,6])
print(n.where(a % 2 == 0))

(array([1, 2, 5], dtype=int64),)
(array([1, 3, 5], dtype=int64),)


In [68]:
a = n.array([[1,2,3],[4,3,6],[3,8,9]])
print(n.where(a == 3))

(array([0, 1, 2], dtype=int64), array([2, 1, 0], dtype=int64))


In [69]:
a = n.array([[[1,2,3],[4,3,6],[3,8,9]]])
print(n.where(a == 3))

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64), array([2, 1, 0], dtype=int64))


## sort()

In [70]:
a = n.array([[1,3,1],[5,2,3]])
print(n.sort(a))

[[1 1 3]
 [2 3 5]]


In [75]:
a = n.array([[1,3,1],[5,2,3]])
print(n.sort(a, 0))

[[1 2 1]
 [5 3 3]]


In [76]:
a = n.array([[1,3,True],[5,2,False]])
print(n.sort(a, 0))

[[1 2 0]
 [5 3 1]]


In [82]:
a = n.array([[1,2,3],[4,5,6]])
print(n.sort(a, None))

[1 2 3 4 5 6]


In [77]:
a = n.array([1,2,3,4,5,6])
for i in a:
    print(i)

1
2
3
4
5


In [78]:
a = n.array([[1,2,3],[4,5,6]])
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6


In [80]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [81]:
a = n.array([[[1,2,3],[4,5,6]]])
for i in n.nditer(a):
    print(i)

1
2
3
4
5
6


# Abstraction

In [83]:
import abc
dir(abc)

['ABC',
 'ABCMeta',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_abc_init',
 '_abc_instancecheck',
 '_abc_register',
 '_abc_subclasscheck',
 '_get_dump',
 '_reset_caches',
 '_reset_registry',
 'abstractclassmethod',
 'abstractmethod',
 'abstractproperty',
 'abstractstaticmethod',
 'get_cache_token']

In [94]:
from abc import ABC, abstractmethod

class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name = shape_name
        
    @abstractmethod
    def draw(self):
        pass
        
class Circle(Shape):
    def __init__(self):
        super().__init__("circle")
    
    def draw(self):
        print("Circle")
        
class Triangle(Shape):
    def __init__(self):
        super().__init__("triangle")
    
    def draw(self):
        print("Triangle")
        
x = Circle()
y = Triangle()
x.draw()
y.draw()

Circle
Triangle


In [93]:
from abc import ABC, abstractmethod

class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name = shape_name
        
    @abstractmethod
    def draw(self):
        pass
        
class Circle(Shape):
    def __init__(self):
        super().__init__("circle")
    
    def draw1(self):
        print("Circle")
        
        
x = Circle()
x.draw1()

TypeError: Can't instantiate abstract class Circle with abstract methods draw