# CH-9 Advanced OOPs:


Polymorphism: 

polymorphism comes from greek word: poly means "many" and morpho means "form".

Archiving polymorphism using:

1.Duck typing
2.Method overriding (Inheritance): 2-class same method with same parameters
3.Operator overloading
4.Method overloading : 1-class same method with different parameters

## Operator overloading: 

In [5]:
print(1+2)
print("1"+"2")
print("Keval"*3)

print(int.__add__(1,2))
print(str.__add__("1","2"))
print(str.__mul__("Keval",3))

3
12
KevalKevalKeval
3
12
KevalKevalKeval


In [8]:
#operator overloading for complex numbers:
#Arithmetic operators

class Complex:
    def __init__(self,r,i):
        self.real=r
        self.imaginary=i
    
    def __add__(self,other): #self vs other
        real=self.real+other.real
        ima=self.imaginary+other.imaginary
        return f"{real}+{ima}i"
        
c1=Complex(1,4)
c2=Complex(3,5)
print(c1+c2)

4+9i


In [9]:
#Comparision operators

class A:
    def __init__(self,a):
        self.a=a
        
    def __gt__(self,other):
        if self.a>other.a:
            return f"{self.a} is higher"
        else:
            return f"{other.a} is higher"
        
x=A(4)
y=A(3)
print(x>y)

4 is higher


## Method overloading: 

In [14]:
class Addition:
    def sum(self,a,b):
        return a+b
    def sum(self,a,b,c):
        return a+b+c
    
obj=Addition()
obj.sum(3,4)
obj.sum(3,4,7)

TypeError: sum() missing 1 required positional argument: 'c'

In [16]:
class Addition:
    def sum(self,a,b):
        return a+b
    def sum(self,a,b,c=5):
        return a+b+c
    
obj=Addition()
print(obj.sum(3,4))
print(obj.sum(3,4,7))

12
14


In [19]:
class Addition:
    def sum(self,a,b):
        return a+b
    def sum(self,*args):
        total=0
        for i in args:
            total+=i
        print(total)
    
obj=Addition()
obj.sum(3,4,8,6)
obj.sum(3,4,7)

21
14


## Method overriding: (Inheritance)

1.single inheritance
2.multiple inheritance
3.multilevel inheritance
4.hybrid inheritance
5.hierarchical inheritance
MRO:Method Resolution Order

### Single inheritance: 

In [21]:
class parent:
    def sleep(self):
        print("Sleep at 9 PM")
        
class child:
    def sleep(self):
        print("Sleep at 12 AM")
    def eat(self):
        print("eat only pizzas")
        
obj=parent()
obj.sleep()

Sleep at 9 PM


In [25]:
class parent:
    def sleep(self):
        print("Sleep at 9 PM")
        
class child(parent):
    def sleep(self):
        print("Sleep at 12 AM")
        super().sleep()
    def eat(self):
        print("eat only pizzas")
        
obj=child()
obj.sleep()

Sleep at 12 AM
Sleep at 9 PM


In [28]:
class parent:
    def sleep(self):
        print("Sleep at 9 PM")
        
class child(parent):
    def swim(self):
        print("swim at 12 AM")
    def eat(self):
        print("eat only pizzas")
        
obj=child()
obj.sleep()
print(parent.mro())

Sleep at 9 PM
[<class '__main__.parent'>, <class 'object'>]


### Multiple inheritance: 

In [32]:
class Father:
    def sleep(self):
        print("Sleep at 9 PM")
    def swim(self):
        print("swim at 6 AM")
        
class Mother:
    def cook(self):
        print("cook very good")
    def sleep(self):
        print("sleep at 10 PM")

class Child(Father,Mother):
    def run(self):
        print("run very fast")
        
x=Child()
x.run()
x.sleep()
print(Child.mro())

run very fast
Sleep at 9 PM
[<class '__main__.Child'>, <class '__main__.Father'>, <class '__main__.Mother'>, <class 'object'>]


In [34]:
class Father:
    def sleep(self):
        print("Sleep at 9 PM")
    def swim(self):
        print("swim at 6 AM")
        
class Mother:
    def cook(self):
        print("cook very good")
    def sleep(self):
        print("sleep at 10 PM")

class Child(Mother,Father):
    def run(self):
        print("run very fast")
        
x=Child()
x.run()
x.sleep()
print(Child.mro())

run very fast
sleep at 10 PM
[<class '__main__.Child'>, <class '__main__.Mother'>, <class '__main__.Father'>, <class 'object'>]


### Multilevel inheritance: 

In [40]:
class Grandfather:
    def sleep(self):
        print("Sleep at 9 PM")
    def swim(self):
        print("swim at 6 AM")
        
class Father(Grandfather):
    def cook(self):
        print("cook very good")
    def sleep(self):
        print("sleep at 10 PM")

class Child(Father):
    def run(self):
        print("run very fast")
        
x=Child()
x.run()
x.sleep()
print(Child.mro())

run very fast
sleep at 10 PM
[<class '__main__.Child'>, <class '__main__.Father'>, <class '__main__.Grandfather'>, <class 'object'>]


### Hierarchical inheritance: 

In [2]:
class Parent:
    def display(self):
        print("display from parent class.")
        
class Child1(Parent):
        def fun(self):
            print("Fun from child class.")
            
class Child2(Parent):
        def show(self):
            print("show from child2 class.")
            
obj=Child1()
obj.display()
obj2=Child2()
obj2.show()
print(Child1.mro())

display from parent class.
show from child2 class.
[<class '__main__.Child1'>, <class '__main__.Parent'>, <class 'object'>]


### Hybrid inharitance: 

In [5]:
class Parent1:
    def display(self):
        print("display from parent1 class.")
        
class Parent2:
    def cook(self):
        print("cook very good.")
        
class Child(Parent1,Parent2):
    def show(self):
            print("show from child class.")
            
class GC1(Child):
    def fun(self):
            print("Fun from GC1 class.") 
    
class GC2(Child):
    def fun2(self):
            print("Fun from GC2 class.") 
            
obj=GC1()
obj.cook()
obj2=GC2()
obj2.display()

cook very good.
display from parent1 class.


### Classic diamond problem (MRO): 

In [8]:
class P1:
    def show(self):
        print("Display from p1.")
        
class P2:
    def fun(self):
        print("Display from p2.")
        
class C1(P1):
    def foo(self):
        print("Display from C1.")
        
class C2(P2):
    def boo(self):
        print("Display from C2.")
        
class GC(C1,C2):
    def display(self):
        print("Display from GC.")
        
obj1=GC()
print(GC.mro())

[<class '__main__.GC'>, <class '__main__.C1'>, <class '__main__.P1'>, <class '__main__.C2'>, <class '__main__.P2'>, <class 'object'>]


In [9]:
class P1:
    def show(self):
        print("Display from p1.")
        
class P2:
    def fun(self):
        print("Display from p2.")
        
class C1(P1,P2):
    def foo(self):
        print("Display from C1.")
        
class C2(P1,P2):
    def boo(self):
        print("Display from C2.")
        
class GC(C1,C2):
    def display(self):
        print("Display from GC.")
        
obj1=GC()
print(GC.mro())

[<class '__main__.GC'>, <class '__main__.C1'>, <class '__main__.C2'>, <class '__main__.P1'>, <class '__main__.P2'>, <class 'object'>]


In [10]:
class P1:
    def show(self):
        print("Display from p1.")
        
class P2:
    def fun(self):
        print("Display from p2.")
        
class C1(P1,P2):
    def foo(self):
        print("Display from C1.")
        
class C2(P2,P1):
    def boo(self):
        print("Display from C2.")
        
class GC(C1,C2):
    def display(self):
        print("Display from GC.")
        
obj1=GC()
print(GC.mro())

TypeError: Cannot create a consistent method resolution
order (MRO) for bases P1, P2

In [12]:
class P1:
    def show(self):
        print("Display from p1.")
        
class P2:
    def fun(self):
        print("Display from p2.")
        
class C1(P1,P2):
    def foo(self):
        print("Display from C1.")
        
class C2(P1):
    def boo(self):
        print("Display from C2.")
        
class GC(C1,C2):
    def display(self):
        print("Display from GC.")
        
obj1=GC()
print(GC.mro())

[<class '__main__.GC'>, <class '__main__.C1'>, <class '__main__.C2'>, <class '__main__.P1'>, <class '__main__.P2'>, <class 'object'>]


In [13]:
class P1:
    def show(self):
        print("Display from p1.")
        
class P2:
    def fun(self):
        print("Display from p2.")
        
class C1(P1,P2):
    def foo(self):
        print("Display from C1.")
        
class C2(P2):
    def boo(self):
        print("Display from C2.")
        
class GC(C1,C2):
    def display(self):
        print("Display from GC.")
        
obj1=GC()
print(GC.mro())

[<class '__main__.GC'>, <class '__main__.C1'>, <class '__main__.P1'>, <class '__main__.C2'>, <class '__main__.P2'>, <class 'object'>]


## Array: 

In [14]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [17]:
d=range(100)
print(d)
import sys 
dir(sys)
sys.getsizeof(d)

range(0, 100)


48

In [20]:
import numpy as np

arr=np.arange(100)
print(arr)
print(arr.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
4


In [22]:
import numpy as np

arr=np.array(42)
print(arr)
print(arr.ndim)

arr1=np.array([42])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

arr2=np.array([[42]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

arr3=np.array([[[42]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)


42
0
[42]
1
(1,)
[[42]]
2
(1, 1)
[[[42]]]
3
(1, 1, 1)


In [24]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr.ndim)
print(arr.shape)

arr1=np.array([[1,2,3],[4,5,6]])
print(arr1.ndim)
print(arr1.shape)

arr2=np.array([[1,2,3],[4,5]]) #VisibleDeprecationWarning
print(arr2.ndim)
print(arr2.shape)

arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3.ndim)
print(arr3.shape)

1
(5,)
2
(2, 3)
1
(2,)
3
(2, 2, 2)


<ipython-input-24-2527e18989d0>:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr2=np.array([[1,2,3],[4,5]])


### Accessing the elements of Array:

In [29]:
import numpy as np

arr=np.array([1,4,9,6,3,2])
print(arr[3])
d=arr[1:2]
print(d)
print(d.shape)

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[1])
print(arr1[1,1])
print(arr1[1,0:2])
print(arr1[0:2,0:2])

arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2[1,0,2])
print(arr2[1,0:2,2])
print(arr2[1,0:2,0:2])
print(arr2[0:2,1,1:2])
print(arr2[0:2,0:2,1])
print(arr2[0:2,0:2,0:1])

6
[4]
(1,)
[4 5 6]
5
[4 5]
[[1 2]
 [4 5]]
9
[ 9 12]
[[ 7  8]
 [10 11]]
[[ 5]
 [11]]
[[ 2  5]
 [ 8 11]]
[[[ 1]
  [ 4]]

 [[ 7]
  [10]]]


In [30]:
import numpy as np

arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


### Reshape: 

In [33]:
import numpy as np

arr=np.array([1,2,3,4,5])
# arr1=arr.reshape(2,3) ValueError: cannot reshape array of size 5 into shape (2,3)
arr1=arr.reshape(5,1)
print(arr1)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [34]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
arr1=arr.reshape(2,3) 
print(arr1)

[[1 2 3]
 [4 5 6]]


In [41]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
arr1=arr.reshape(3,-1)
print(arr1)

arr2=arr.reshape(3,-1).base
print(arr2)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [42]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
arr1=arr.reshape(2,3,-1)
print(arr1)


[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


# concatenate(), split(), where(), sort()

## concatenate()

In [2]:
import numpy as n
arr = n.array([1,2,3])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
a1 = n.array([1,2,3])
a2 = n.array([4,5,6])
a3 = n.array([7,8,9])
newAr = n.concatenate((a1,a2,a3))
print(newAr)

[1 2 3 4 5 6 7 8 9]


In [4]:
a1 = n.array([1,2,3])
a2 = n.array([4,5,6])
a3 = n.array([7,8,9])
newAr = n.concatenate((a1,a2,a3),1)
print(newAr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [5]:
a1 = n.array([[1,2],[3,4]])
a2 = n.array([[5,6],[7,8]])
newAr = n.concatenate((a1,a2))
print(newAr)
print()
newAr = n.concatenate((a1,a2),1)
print(newAr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
a1 = n.array([[[1,2],[3,4]]])
a2 = n.array([[[1,2],[3,4]]])

newAr = n.concatenate((a1,a2))
print(newAr)
print()
newAr = n.concatenate((a1,a2),2)
print(newAr)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

[[[1 2 1 2]
  [3 4 3 4]]]


## split()

In [7]:
a = n.array([1,2,3,4,5,6])

print(n.array_split(a,3))
print(n.array_split(a,2))
print(n.array_split(a,4))
print(n.array_split(a,10))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [8]:
a = n.array([[1,2,3],[4,5,6],[7,8,9]])
print(n.array_split(a,2))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [9]:
a = n.array([[1,2,3],[4,5,6],[7,8,9]])
print(n.array_split(a,3,1))
print()
print(n.array_split(a,4,1))

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]]), array([], shape=(3, 0), dtype=int32)]


In [10]:
a = n.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(n.array_split(a,2,1))

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[7, 8, 9]]])]


## where()

In [11]:
a = n.array([1,3,3,4,5,3])
print(n.where(a == 3))
a = n.array([1,2,3,4,5,6])
print(n.where(a % 2 == 0))

(array([1, 2, 5], dtype=int64),)
(array([1, 3, 5], dtype=int64),)


In [12]:
a = n.array([[1,2,3],[4,3,6],[3,8,9]])
print(n.where(a == 3))

(array([0, 1, 2], dtype=int64), array([2, 1, 0], dtype=int64))


In [13]:
a = n.array([[[1,2,3],[4,3,6],[3,8,9]]])
print(n.where(a == 3))

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64), array([2, 1, 0], dtype=int64))


## sort()

In [14]:
a = n.array([[1,3,1],[5,2,3]])
print(n.sort(a))

[[1 1 3]
 [2 3 5]]


In [15]:
a = n.array([[1,3,1],[5,2,3]])
print(n.sort(a, 0))

[[1 2 1]
 [5 3 3]]


In [16]:
a = n.array([[1,3,True],[5,2,False]])
print(n.sort(a, 0))

[[1 2 0]
 [5 3 1]]


In [17]:
a = n.array([[1,2,3],[4,5,6]])
print(n.sort(a, None))

[1 2 3 4 5 6]


In [18]:
a = n.array([1,2,3,4,5,6])
for i in a:
    print(i)

1
2
3
4
5
6


In [19]:
a = n.array([[1,2,3],[4,5,6]])
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6


In [20]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [21]:
a = n.array([[[1,2,3],[4,5,6]]])
for i in n.nditer(a):
    print(i)

1
2
3
4
5
6


# Abstraction

In [22]:
import abc
dir(abc)

['ABC',
 'ABCMeta',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_abc_init',
 '_abc_instancecheck',
 '_abc_register',
 '_abc_subclasscheck',
 '_get_dump',
 '_reset_caches',
 '_reset_registry',
 'abstractclassmethod',
 'abstractmethod',
 'abstractproperty',
 'abstractstaticmethod',
 'get_cache_token']

In [23]:
from abc import ABC, abstractmethod

class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name = shape_name
        
    @abstractmethod
    def draw(self):
        pass
        
class Circle(Shape):
    def __init__(self):
        super().__init__("circle")
    
    def draw(self):
        print("Circle")
        
class Triangle(Shape):
    def __init__(self):
        super().__init__("triangle")
    
    def draw(self):
        print("Triangle")
        
x = Circle()
y = Triangle()
x.draw()
y.draw()

Circle
Triangle


In [24]:
from abc import ABC, abstractmethod

class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name = shape_name
        
    @abstractmethod
    def draw(self):
        pass
        
class Circle(Shape):
    def __init__(self):
        super().__init__("circle")
    
    def draw1(self):
        print("Circle")
        
        
x = Circle()
x.draw1()

TypeError: Can't instantiate abstract class Circle with abstract methods draw